name: gomawo_app
description: "곰아워 Flutter 앱 (웹앱 래퍼)"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true
